on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container: 1maa/erlang:23-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install build dependencies
        run: apk add build-base libsodium-dev

      - name: Run EUnit tests
        run: rebar3 as test eunit

      - name: Run ProPer tests
        run: rebar3 as test proper -n 10000
